### ISSUE TITLE
Modificación del módulo Visualizer

### ISSUE THREAD

**Issue by Alebarmor** [enderfews/EGC_Majaceite#66]
Se va a añadir un nuevo campo de información para el votante que defina si este está desempleado o no. A su vez, también habrá de añadirse en el módulo la gráfica correspondiente, tal y como los otros campos de información tienen también, junto con sus correspondientes pruebas.

Soluciones propuestas:
- Se propone seguir el procedimiento realizado para los demás campos:
	1. Cargar un nuevo CSV con el nuevo campo de información generado
	2. Añadir al módulo Visualizer la adición de este campo y su correspondiente gráfica
	3. Crear los test correspondientes para verificar que la modificación funciona como se esperaba

---
**Autor incidencia**: Alejandro Barba Moreno
**Estado**:  Verified
**Prioridad**:  Medium
**Tipo**: Mejora
**Rol de encargado**: Programador

**Comment by juapormon** [comment]
Se ha implementado la mejora y se ha realizado un test de selenium para probarla
